import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
const root='/Users/noellemaingi/Documents/trading';
const skill='/Users/noellemaingi/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const py='/Users/noellemaingi/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
const out=path.join(root,'deck-output','commodity-module-tech-demo-v5.pptx');
const {finalizePresentation}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')).href);
const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={paper:'#F7F5EF',ink:'#142333',muted:'#4A5967',blue:'#1D425F',rust:'#B95A38',white:'#FFFFFF'};
const F={head:'Georgia',body:'Arial'};
function t(s,v,x,y,w,h,size,color=C.ink,bold=false,font=F.body){const z=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});z.text=v;z.text.style={typeface:font,fontSize:size,bold,color,autoFit:'none'};return z}
function page(n,k,title,sub=''){const s=p.slides.add();s.background.fill=C.paper;t(s,k.toUpperCase(),72,45,1040,30,17,C.rust,true);t(s,title,72,94,1138,88,47,C.ink,false,F.head);if(sub)t(s,sub,74,191,1100,61,22,C.muted);t(s,String(n).padStart(2,'0'),1172,665,40,26,16,C.muted);return s}
function col(s,h,b,x,y,w,bs=22){t(s,h,x,y,w,43,26,C.blue,true);t(s,b,x,y+51,w,178,bs,C.ink)}
function band(s,v,y=586,size=25){t(s,v,76,y,1115,90,size,C.rust,true)}
function note(s,v){s.speakerNotes.textFrame.setText(v)}
const src='Source: product/commodity_trading/ele_trading/README.md';
// 1
{const s=p.slides.add();s.background.fill=C.ink;t(s,'ELEWA / ENGINEERING SHOWCASE',77,58,1000,32,19,'#DAB29D',true);t(s,"When the Standard Way\nIsn't Enough:\nAn Odoo Story",74,145,1130,275,65,C.white,false,F.head);t(s,'The commodity trading module',79,478,1050,55,31,C.white);t(s,'Product story  /  architecture  /  live demo',80,633,1000,30,19,'#DAB29D');note(s,src+' and product/commodity_trading/ele_trading_budget/README.md.');}
// 2
{const s=page(2,'Today','Agenda');col(s,'01  Where standard Odoo stops','The gap between order records and a commodity position.',80,220,495);col(s,'02  What I added','The Trade model and the Odoo events that update it.',675,220,495);col(s,'03  What it calculates','Position, P&L, currency, costs and stock.',80,452,495);col(s,'04  What I will show','A live path through the workflow, reporting and extensions.',675,452,495);note(s,'Agenda for the engineering demonstration.');}
// 3
{const s=page(3,'Where the standard way stops','Orders do not describe a whole trade','Standard Odoo treats a purchase and sale as separate documents. A commodity position spans both.');col(s,'Fragmented activity','One purchase can be sold in parts across dates, prices and currencies.',76,301,345);col(s,'Hidden exposure','The remaining open quantity and paper P&L are hard to see from orders alone.',466,301,345);col(s,'Incomplete profit','Freight, storage and other bills change the real economics.',856,301,345);band(s,'This is why the standard document flow was not enough.',586,25);note(s,src+', sections 1 and 2.');}
// 4
{const s=page(4,'What I added','One Trade record connects the documents','Users stay in normal Odoo screens. The module responds to document lifecycle events.');col(s,'Orders','Purchase confirmation creates or updates a long trade. Sale confirmation links a trade or opens a short one.',76,297,345,21);col(s,'Financials','Posted bills and invoices feed additional cost or revenue into the trade.',466,297,345,21);col(s,'Stock','Validated receipts connect lots to the trade for physical on-hand quantity.',856,297,345,21);band(s,'The Trade record is the shared identity across these models.',586,25);note(s,src+', sections 3 and 4. Implementation: purchase_order.py, sale_order.py, account_move_lifecycle.py, stock_picking.py.');}
// 5
{const s=page(5,'Lifecycle','A position changes as the deal progresses','Long and short trades share one reporting surface, with different opening paths.');col(s,'Open long','Confirm a purchase order. The trade captures product, quantity, price and currency.',76,301,345);col(s,'Sell down','Confirm one or more sales. Sold quantity, open position and realized P&L recompute.',466,301,345);col(s,'Close','A confirmed trade closes automatically when its matching condition is met.',856,301,345);band(s,'A sale without a matching open trade can create a short trade.',584,25);note(s,src+', sections 4 and 6. Short-trade closure uses a separate condition from the long-trade fully-matched flag.');}
// 6
{const s=page(6,'Live demo','The path I will show in Odoo','Each step should leave a visible change on the Trade record.');col(s,'1  Purchase','Confirm a tracked commodity. Open the linked Trade and check the purchase leg.',76,286,335,21);col(s,'2  Partial sale','Confirm a sale. Watch sold quantity and open position change.',466,286,335,21);col(s,'3  Price + bill','Enter a market price, then post a linked bill. Review P&L and extra cost.',856,286,335,21);band(s,'Finish in Trading Reporting with list, graph and pivot views.',585,25);note(s,'Presenter cue. Requires an Odoo environment with suitable sample product, partner, purchase order, sale order, and bill. Do not present this as a screenshot of a real environment.');}
// 7
{const s=page(7,'Position engine','The quantities answer two separate questions','The commercial position comes from orders. Physical on-hand comes from stock lots.');col(s,'Commercial open','Purchased quantity minus total confirmed sold quantity. Positive is long exposure, negative is short.',76,295,520);col(s,'Physical on hand','Quantity from lots linked through validated incoming stock pickings.',677,295,520);band(s,'They can differ while receipts or deliveries are still in progress.',567,25);note(s,src+', sections 5 and 9. Implementation: trading_trade_pnl.py and stock_picking.py.');}
// 8
{const s=page(8,'P&L engine','Matched units and open units are priced separately','All monetary calculations use the reporting currency.');col(s,'Average cost per unit','(Purchase quantity × converted purchase price + additional costs) ÷ purchase quantity',76,285,345,21);col(s,'Realized P&L','Converted sales value less average cost of the matched quantity.',466,285,345,21);col(s,'Unrealized P&L','Open quantity × spread between market price and cost for a long position.',856,285,345,21);band(s,'Total P&L = realized + unrealized + additional revenue.',586,25);note(s,src+', section 6. For short positions the unrealized formula uses sale price less market price. Without a market price, a long position shows a conservative negative cost exposure placeholder; a short shows zero.');}
// 9
{const s=page(9,'Worked example','A partial sale in numbers','Illustrative long trade in one reporting currency. No additional revenue.');t(s,'100 units',77,281,305,52,42,C.blue,true);t(s,'bought at 10',78,337,300,40,22,C.muted);t(s,'40 units',477,281,305,52,42,C.blue,true);t(s,'sold at 14',478,337,300,40,22,C.muted);t(s,'60 units',877,281,305,52,42,C.rust,true);t(s,'open at market price 12',878,337,320,65,21,C.muted);col(s,'Extra cost: 100','Average cost becomes 11 per unit.',76,449,310,21);col(s,'Realized','40 × (14 − 11) = 120.',466,449,310,21);col(s,'Unrealized','60 × (12 − 11) = 60.',856,449,310,21);band(s,'Total P&L = 180.',588,25);note(s,'Illustrative arithmetic only. Formula basis: ele_trading README, section 6. Market price is manually entered.');}
// 10
{const s=page(10,'Currency and invoices','The financial picture follows source dates','The module records a transaction in its own currency, then converts it for comparison.');col(s,'Historical FX','Each sale uses the exchange rate on its own order date. A blended sale price uses the reporting currency when sales span currencies.',76,288,520,21);col(s,'Invoice lifecycle','Linked bills or invoices add cost or revenue. Resetting to draft or unlinking reverses the contribution.',679,288,520,21);band(s,'The trade remains traceable to the documents behind the number.',583,25);note(s,src+', sections 4 and 7. Implementation: trading_trade_pricing.py and account_move_lifecycle.py.');}
// 11
{const s=page(11,'Contracts','Futures sit under the parent trade','Contract tracking is separate from the trade’s order bookkeeping.');col(s,'Terms and balance','A contract records price and quantity, plus delivered and open balance.',76,300,345);col(s,'Realized P&L','Compares actual sales value with contract value for the delivered quantity.',466,300,345);col(s,'Unrealized P&L','Uses the parent trade direction and current market price for the undelivered portion.',856,300,345);band(s,'This is a feature to show after the core position demo.',585,25);note(s,src+', section 8. The future delivery line model exists, but its parent One2many link is currently commented out. Avoid claiming the delivery lines are browseable from the parent futures record.');}
// 12
{const s=page(12,'Optional extension','Trade Budgets adds planned versus actual','It is a separately installable addon layered on top of core Trading.');col(s,'Plan','One budget per trade holds budgeted or target cost and revenue, using the target margin.',76,290,345,21);col(s,'Actuals','Posted bills, invoices and expenses populate actual cost and revenue lines.',466,290,345,21);col(s,'Variance','The cost and revenue variance appears once the trade is fully matched.',856,290,345,21);band(s,'Core Trading continues to work when the budget addon is absent.',586,25);note(s,'Source: product/commodity_trading/ele_trading_budget/README.md.');}
// 13
{const s=page(13,'Reporting surface','The result is inspectable from several angles','A trade form supports investigation; reporting views support comparison.');col(s,'Trade form','Open and closed position summaries show quantity, cost basis and P&L. Smart buttons reach linked documents.',76,285,520,21);col(s,'Reporting','List, Kanban, graph and pivot views. Filters include trade type, status, profitability and fully matched.',678,285,520,21);band(s,'In the demo, open the source documents from the Trade before showing aggregate views.',574,24);note(s,src+', section 10. Verified in views/trading_trade_views.xml and views/menu.xml.');}
// 14
{const s=page(14,'Engineering choices','Why the design is interesting','The strongest part is making existing workflows produce a coherent position.');col(s,'Event driven sync','Order confirmation, invoice posting and stock validation drive updates.',76,290,345,21);col(s,'One identity','Purchase, sale, invoice and stock records link back to the Trade.',466,290,345,21);col(s,'Explicit economics','Stored computed measures expose position, cost basis and P&L in views and reports.',856,290,345,21);band(s,'Users do not need to re-enter a trade after doing the operational work.',583,25);note(s,src+', sections 1, 3 and 5. Implementation files across product/commodity_trading/ele_trading/models.');}
// 15
{const s=page(15,'Current edges','What I would harden next','The module is functional, with a few areas worth discussing as engineers.');col(s,'Financial tests','The core P&L calculation needs broader automated coverage before higher volume reliance.',76,285,335,21);col(s,'Scale','Dependent field recomputation has not been load-tested at high trade volume.',466,285,335,21);col(s,'Bill reversal','A direct vendor bill with a matching product has a partial draft reversal gap.',856,285,335,21);band(s,'These are the next engineering steps, not hidden assumptions.',580,25);note(s,src+', sections 12 and 13. README says no automated P&L-engine coverage; the repository does contain tests for related order, invoice, and budget paths.');}
// 16
{const s=p.slides.add();s.background.fill=C.ink;t(s,'THE TAKEAWAY',77,57,1000,31,19,'#DAB29D',true);t(s,'One trade.\nThe whole story.',75,166,1080,205,82,C.white,false,F.head);t(s,'Standard Odoo supplies the orders and invoices. This module connects them into a live commodity position.',80,465,1070,117,30,C.white);t(s,'Now let me show you the actual workflow.',81,621,1030,37,24,'#DAB29D',true);note(s,'Closing cue for the live demonstration.');}

const stage=path.join(root,'.codex-finalizer');await fs.mkdir(stage,{recursive:true});await fs.mkdir(path.dirname(out),{recursive:true});const candidate=path.join(stage,'candidate-tech.pptx');await (await PresentationFile.exportPptx(p)).save(candidate);
const result=await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:out,pythonExecutable:py,integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],fontPolicy:{basis:'design',families:[F.head,F.body]},verifyArtifactToolImport:true,receiptPath:path.join(stage,'commodity-module-tech-v5.validation.json')});console.log(JSON.stringify({path:result.finalPath,slides:result.packageIntegrity?.slide_count,layoutFindings:result.presentationLayout?.finding_count}));
