import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Presentation,PresentationFile} from '@oai/artifact-tool';

const root='/Users/noellemaingi/Documents/trading';
const skill='/Users/noellemaingi/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const py='/Users/noellemaingi/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
const out=path.join(root,'deck-output','commodity-module-simple-tech-demo-v4.pptx');
const {finalizePresentation}=await import(pathToFileURL(path.join(skill,'container_tools/artifact_tool_utils.mjs')).href);
const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={paper:'#F7F5EF',ink:'#142333',muted:'#4A5967',blue:'#1D425F',rust:'#B95A38',white:'#FFFFFF'};
const F={head:'Georgia',body:'Arial'};
function text(s,v,x,y,w,h,size,color=C.ink,bold=false,font=F.body){const z=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});z.text=v;z.text.style={typeface:font,fontSize:size,bold,color,autoFit:'none'};return z}
function slide(n,kicker,title,sub=''){const s=p.slides.add();s.background.fill=C.paper;text(s,kicker.toUpperCase(),75,45,1050,32,17,C.rust,true);text(s,title,75,100,1120,87,48,C.ink,false,F.head);if(sub)text(s,sub,77,202,1090,60,23,C.muted);text(s,String(n).padStart(2,'0'),1172,665,40,27,16,C.muted);return s}
function bit(s,h,b,x,y,w){text(s,h,x,y,w,45,27,C.blue,true);text(s,b,x,y+57,w,148,23,C.ink)}
function big(s,v,x,y,w,color=C.blue){text(s,v,x,y,w,105,72,color,true)}
function note(s,v){s.speakerNotes.textFrame.setText(v)}
const src='Source: product/commodity_trading/ele_trading/README.md';

// 1
{const s=p.slides.add();s.background.fill=C.ink;text(s,'AN ODOO PRODUCT STORY',80,57,1000,31,19,'#DAB29D',true);text(s,"When the Standard Way\nIsn't Enough:\nAn Odoo Story",78,145,1120,275,64,C.white,false,F.head);text(s,'The commodity trading module',82,487,1050,54,31,C.white);text(s,'A simple walkthrough for the tech team',82,628,1000,32,20,'#DAB29D');note(s,'Presentation based on the commodity trading module in this repository.');}
// 2
{const s=slide(2,'The plan','Agenda');bit(s,'1  The business','What commodity trading means and why one trade spans several documents.',83,234,500);bit(s,'2  The gap','What standard Odoo records show, and what they leave for us to work out.',678,234,500);bit(s,'3  The module','How the Trade record follows the deal and calculates its result.',83,467,500);bit(s,'4  The demo','A short path through the Odoo screens and the key numbers.',678,467,500);note(s,'Agenda.');}
// 3
{const s=slide(3,'First, the domain','What is commodity trading?','It is buying and selling physical goods whose prices change in the market.');bit(s,'Examples','Cocoa, coffee, grain and fuel are commodities.',80,314,340);bit(s,'The deal','A trader buys a quantity, then may sell it in parts over time.',470,314,340);bit(s,'The question','What is still open, and are we making or losing money?',860,314,340);text(s,'For this demo, think of one batch of cocoa sold across several orders.',80,591,1080,60,25,C.rust,true);note(s,'General domain explanation, illustrated with cocoa. This is not a claim about a particular live trade.');}
// 4
{const s=slide(4,'A small example','One purchase can become several sales','Illustrative example using generic units.');big(s,'100',82,303,300);text(s,'units bought',84,398,270,40,24,C.muted);big(s,'40',478,303,300);text(s,'units sold today',480,398,300,40,24,C.muted);big(s,'60',875,303,300,C.rust);text(s,'units still open',878,398,300,40,24,C.muted);text(s,'The 60 open units are the position we still need to manage.',82,567,1080,65,28,C.rust,true);note(s,'Illustrative quantity example only. A position is the amount purchased but not yet sold for this simple long-trade example.');}
// 5
{const s=slide(5,'A fair question','Could an analytic account do this?','Yes, it can group costs and revenue attributed to a trade. That solves part of the problem.');bit(s,'Analytic account','Shows attributed accounting costs and revenue, so we can analyze the financial result.',80,305,505);bit(s,'Trade record','Links confirmed orders and shows what is still open, estimated P&L and physical stock.',680,305,505);text(s,'The Trade adds the live position that an analytic account does not calculate for us.',82,558,1090,84,27,C.rust,true);note(s,src+', sections 1, 2 and 5. Odoo 19 analytic-account documentation: https://www.odoo.com/documentation/19.0/applications/finance/accounting/reporting/analytic_accounting.html. Analytic accounts summarize attributed costs and revenue from accounting entries. The optional Trade Budget addon has an analytic account field documented as intended for future accounting integration; this slide does not claim that the Trade automatically populates an analytic account.');}
// 6
{const s=slide(6,'What I built','The Trade record connects the story','The team still works in the usual Odoo purchase and sale screens.');bit(s,'When we buy','A confirmed purchase creates or updates the Trade.',80,307,325);bit(s,'When we sell','A confirmed sale links to the Trade.',470,307,325);bit(s,'Then we see','The Trade updates quantity, costs and profit.',860,307,325);text(s,'One Trade is the place to understand the whole deal.',80,586,1100,65,28,C.rust,true);note(s,src+', sections 1, 3 and 4. If no matching open Trade exists, a confirmed sale can create a short Trade.');}
// 7
{const s=slide(7,'How it follows the deal','The module reacts to work already done','There is no separate trade entry step in the normal flow.');bit(s,'Confirm an order','Purchase and sale confirmations change the Trade.',80,301,340);bit(s,'Post a bill','Linked costs, such as freight, change the result.',470,301,340);bit(s,'Receive stock','Validated goods receipts link lots for physical quantity.',860,301,340);text(s,'The Trade is derived from the source documents, not typed twice.',80,581,1100,65,28,C.rust,true);note(s,src+', sections 3 and 4. Implementation hooks include purchase_order.py, sale_order.py, account_move_lifecycle.py and stock_picking.py.');}
// 8
{const s=slide(8,'What the Trade shows','Four useful numbers','These are the measures to point at in the live demo.');bit(s,'Open position','How much has been bought but not yet sold.',80,280,505);bit(s,'Realized P&L','Profit or loss on the quantity already sold.',680,280,505);bit(s,'Unrealized P&L','Estimated profit or loss on the open quantity, using a market price.',80,477,505);bit(s,'On hand','How much physical stock is linked to the Trade.',680,477,505);note(s,src+', sections 5, 6 and 9. P&L means profit and loss. A user enters the current market price. Commercial open quantity and physical on-hand quantity can differ.');}
// 9
{const s=slide(9,'The numbers, simply','What does profit look like here?','Illustrative long trade in one currency, with no extra costs.');bit(s,'Buy','100 units at 10 each. Total purchase cost: 1,000.',80,288,325);bit(s,'Sell','40 units at 14 each. Sales value: 560.',470,288,325);bit(s,'Already earned','40 × (14 − 10) = 160 realized profit.',860,288,325);text(s,'Open estimate: 60 × (12 market price − 10 cost) = 120 profit.',80,563,1110,85,26,C.rust,true);note(s,'Illustrative arithmetic only, not live data. Formula basis: ele_trading README, section 6. It assumes no extra costs or revenue and a user-entered market price of 12.');}
// 10
{const s=slide(10,'Other real-world details','A trade is more than two prices','These details change what a useful result looks like.');bit(s,'Extra costs','Linked bills can add freight or storage to the trade cost.',80,302,340);bit(s,'Currencies','Each order converts at the exchange rate from its own date.',470,302,340);bit(s,'Physical stock','On-hand quantity comes from linked stock lots, so it can differ from the open position.',860,302,340);text(s,'The goal is a result that reflects the actual deal.',80,586,1100,62,28,C.rust,true);note(s,src+', sections 2, 4, 7 and 9.');}
// 11
{const s=slide(11,'For the tech team','How it is wired into Odoo','The core model is trading.trade. Existing Odoo models carry a link to it.');bit(s,'Order events','Purchase and sale confirmation create or link the Trade.',80,301,340);bit(s,'Accounting events','Posted invoices and bills add cost or revenue. Draft reset reverses them.',470,301,340);bit(s,'Stock events','Validated receipts link lots to the Trade.',860,301,340);text(s,'The module extends existing workflows and recomputes stored Trade measures.',80,579,1110,72,26,C.rust,true);note(s,src+', sections 3 and 5. Implementation: purchase_order.py, sale_order.py, account_move_lifecycle.py, stock_picking.py, trading_trade_pnl.py.');}
// 12
{const s=slide(12,'Beyond the core flow','What else is in the module?','I would show these briefly after the main Trade demo.');bit(s,'Reporting','Trade list, Kanban, graph and pivot views, with filters.',80,290,340);bit(s,'Futures','Contracts under a Trade track agreed quantity, delivery balance and P&L.',470,290,340);bit(s,'Budgets','An optional addon compares planned and actual trade costs and revenue.',860,290,340);text(s,'The main idea stays the same: one Trade links the pieces.',80,583,1100,64,27,C.rust,true);note(s,src+', sections 8 and 10. Budget source: product/commodity_trading/ele_trading_budget/README.md. Budgets are a separate optional addon.');}
// 13
{const s=slide(13,'Live demo','The path through Odoo','Use one prepared example so the audience can follow the same Trade.');bit(s,'1  Buy','Confirm a purchase. Open the new Trade.',80,288,315);bit(s,'2  Sell','Confirm a partial sale. Check what remains.',470,288,315);bit(s,'3  Price','Enter a market price. Check estimated profit.',860,288,315);text(s,'Narrate each change as: document action, Trade update, business meaning.',80,583,1100,70,26,C.rust,true);note(s,'Presenter cue. Prepare sample data in the live Odoo environment before presenting.');}
// 14
{const s=p.slides.add();s.background.fill=C.ink;text(s,'THE POINT',80,60,1000,31,19,'#DAB29D',true);text(s,'One trade.\nThe whole story.',78,177,1080,205,82,C.white,false,F.head);text(s,'When ordinary Odoo documents were not enough to describe a commodity position, I built the Trade that connects them.',82,476,1070,110,29,C.white);text(s,'Now I can show you that story in the system.',83,626,1050,39,23,'#DAB29D',true);note(s,'Closing cue for the live demo.');}

const stage=path.join(root,'.codex-finalizer');await fs.mkdir(stage,{recursive:true});await fs.mkdir(path.dirname(out),{recursive:true});const candidate=path.join(stage,'candidate-simple.pptx');await (await PresentationFile.exportPptx(p)).save(candidate);
const result=await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:out,pythonExecutable:py,integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],fontPolicy:{basis:'design',families:[F.head,F.body]},verifyArtifactToolImport:true,receiptPath:path.join(stage,'commodity-module-simple-v4.validation.json')});console.log(JSON.stringify({path:result.finalPath,slides:result.packageIntegrity?.slide_count,layoutFindings:result.presentationLayout?.finding_count}));
